
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import OnboardingLayout from "../layout";

export default function TermsPage() {
  const termsContent = `Welcome to Agricure!

These Terms and Conditions outline the rules and regulations for the use of our application.

By accessing and using this app, you accept these terms and conditions in full. Do not continue to use Agricure if you do not accept all of the terms and conditions stated on this page.

**1. License to Use Application**
Unless otherwise stated, Agricure and/or its licensors own the intellectual property rights for all material on Agricure. All intellectual property rights are reserved.

**2. Data Collection and User Consent**
By using this app, you grant Agricure explicit consent to collect, store, and process data you provide, including but not limited to:
a) Personal and Farm Information: Your phone number, email, farm's geographic location (GPS coordinates), soil type, and chosen crops.
b) Camera Access: For the 'Disease Scan' feature, you consent to allow the app to access your device's camera to capture and upload images of your crops for analysis.
c) Usage Data: We may collect data on how you interact with the app to improve our services.

This data is essential for providing you with personalized agricultural advisories, including weather forecasts, market prices, soil health information, and disease risk assessments.

**3. AI-Generated Advisories and Disclaimers**
You acknowledge and agree that:
a) All recommendations, diagnoses, and advisories provided within the app are generated by an Artificial Intelligence (AI) model.
b) This information is for guidance and informational purposes ONLY. It should not be considered a substitute for professional agronomic advice, field verification, or scientific testing.
c) Agricure makes no warranties or guarantees regarding the accuracy, reliability, or completeness of the AI-generated content.
d) You are solely responsible for all decisions, actions, and their consequences related to your farming practices. Agricure and its parent company are not responsible for any crop failure, financial loss, or other damages.

**4. Privacy Policy**
Our Privacy Policy, which is an integral part of these Terms, describes in detail how we handle your data. Key commitments include:
a) We will not sell or rent your personally identifiable information (PII) to third parties for marketing purposes without your explicit consent.
b) Anonymized and aggregated data may be used for research, statistical analysis, and to improve our AI models and services.

**5. Communication Consent**
By providing your contact details, you consent to receive communications from Agricure related to our services. This may include:
a) In-app notifications
b) WhatsApp messages
c) SMS/Text Messages
d) Automated or manual phone calls for critical alerts or support.
You can manage your communication preferences at any time in the app's settings.

**6. Marketplace and Third-Party Services**
The app may include marketplaces for products or equipment. Agricure acts as a facilitator. Any transaction you make is directly with the third-party vendor. We are not a party to such transactions and are not liable for the quality, delivery, or any other aspect of the products or services offered by third parties.

**7. Limitation of Liability**
To the maximum extent permitted by applicable law, in no event shall Agricure, its owners, or employees be liable for any direct, indirect, punitive, incidental, special, or consequential damages or any damages whatsoever, including, without limitation, damages for loss of use, data, crop yield, or profits, arising out of or in any way connected with the use or performance of the application.

**8. Changes to Terms**
Agricure reserves the right to revise these terms and conditions at any time. We will notify you of any significant changes. By continuing to use the app after such changes, you agree to be bound by the revised terms.

By checking the box on the preferences page, you confirm that you have read, understood, and agree to be bound by these Terms and Conditions.
`;

  return (
    <OnboardingLayout>
        <Card className="w-full bg-card/90 backdrop-blur-sm">
        <CardHeader className="items-center text-center">
            <CardTitle className="text-2xl font-headline font-bold">
            Terms and Conditions
            </CardTitle>
            <CardDescription>
            Please review our terms of service.
            </CardDescription>
        </CardHeader>
        <CardContent>
            <ScrollArea className="h-96 rounded-md border p-4 text-sm text-muted-foreground">
                <p className="whitespace-pre-wrap">{termsContent}</p>
            </ScrollArea>
        </CardContent>
        </Card>
    </OnboardingLayout>
  );
}
